packages:
  - "apps/*"
  - "packages/*"
  - "packages/backend/*"
  - "tooling/tsconfig"

blockExoticSubdeps: true
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "effect"
  - "@effect/*"
  - "drizzle-orm"
  - "auth"
  - "better-auth"
  - "@better-auth/*"

allowBuilds:
  "esbuild": true
  "msgpackr-extract": false

catalogs:
  better-auth:
    "auth": 1.7.1
    "better-auth": 1.7.1
    "@better-auth/drizzle-adapter": 1.7.1
  build:
    "typescript": ^7.0.2
    "esbuild": ^0.28.2
  drivers:
    "pg": ^8.23.0
  drizzle:
    "drizzle-orm": 1.0.0-rc.5-169397b
  effect:
    "effect": 4.0.0-beta.105
    "@effect/sql-pg": 4.0.0-beta.105
    "@effect/platform-node": 4.0.0-beta.105
  types:
    "@types/node": ^26.2.0
    "@types/pg": ^8.21.0
  utils:
    "@paralleldrive/cuid2": ^3.3.0
    "@sindresorhus/slugify": ^3.0.0

patchedDependencies:
  "@effect/sql-pg@4.0.0-beta.105": patches/@effect__sql-pg@4.0.0-beta.105.patch
